// <auto-generated />
using System;
using ExerciseA.Implementation.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExerciseA.Implementation.Migrations
{
    [DbContext(typeof(ExerciseAContext))]
    [Migration("20201210083713_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExerciseA.Domain.Entities.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Order");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2020, 12, 3, 11, 9, 44, 554, DateTimeKind.Local).AddTicks(900),
                            CustomerName = "Juan Toy"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2020, 12, 8, 12, 34, 12, 478, DateTimeKind.Local).AddTicks(4990),
                            CustomerName = "Dominic Haag"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedDate = new DateTime(2020, 12, 5, 10, 48, 31, 717, DateTimeKind.Local).AddTicks(3798),
                            CustomerName = "Grady Tromp"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedDate = new DateTime(2020, 12, 6, 5, 1, 41, 328, DateTimeKind.Local).AddTicks(5105),
                            CustomerName = "Tasha Block"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedDate = new DateTime(2020, 12, 3, 19, 2, 1, 262, DateTimeKind.Local).AddTicks(4679),
                            CustomerName = "Israel Hand"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedDate = new DateTime(2020, 12, 9, 8, 20, 30, 697, DateTimeKind.Local).AddTicks(9461),
                            CustomerName = "Kevin Deckow"
                        },
                        new
                        {
                            Id = 7L,
                            CreatedDate = new DateTime(2020, 12, 7, 21, 5, 25, 816, DateTimeKind.Local).AddTicks(1400),
                            CustomerName = "Michelle Paucek"
                        },
                        new
                        {
                            Id = 8L,
                            CreatedDate = new DateTime(2020, 12, 3, 13, 31, 7, 453, DateTimeKind.Local).AddTicks(3530),
                            CustomerName = "Terence Zulauf"
                        },
                        new
                        {
                            Id = 9L,
                            CreatedDate = new DateTime(2020, 12, 6, 9, 10, 0, 374, DateTimeKind.Local).AddTicks(241),
                            CustomerName = "Kathryn Murray"
                        },
                        new
                        {
                            Id = 10L,
                            CreatedDate = new DateTime(2020, 12, 4, 17, 11, 23, 55, DateTimeKind.Local).AddTicks(4072),
                            CustomerName = "Mindy Klocko"
                        },
                        new
                        {
                            Id = 11L,
                            CreatedDate = new DateTime(2020, 12, 4, 11, 10, 33, 802, DateTimeKind.Local).AddTicks(7200),
                            CustomerName = "Tyrone Haag"
                        },
                        new
                        {
                            Id = 12L,
                            CreatedDate = new DateTime(2020, 12, 9, 15, 34, 9, 775, DateTimeKind.Local).AddTicks(3699),
                            CustomerName = "Steven Volkman"
                        },
                        new
                        {
                            Id = 13L,
                            CreatedDate = new DateTime(2020, 12, 9, 15, 17, 33, 130, DateTimeKind.Local).AddTicks(6914),
                            CustomerName = "Christina Roob"
                        },
                        new
                        {
                            Id = 14L,
                            CreatedDate = new DateTime(2020, 12, 4, 2, 3, 52, 96, DateTimeKind.Local).AddTicks(6391),
                            CustomerName = "Lorenzo Senger"
                        },
                        new
                        {
                            Id = 15L,
                            CreatedDate = new DateTime(2020, 12, 5, 16, 29, 40, 676, DateTimeKind.Local).AddTicks(8230),
                            CustomerName = "Pat Cummerata"
                        },
                        new
                        {
                            Id = 16L,
                            CreatedDate = new DateTime(2020, 12, 8, 23, 45, 20, 149, DateTimeKind.Local).AddTicks(603),
                            CustomerName = "Ann Pfeffer"
                        },
                        new
                        {
                            Id = 17L,
                            CreatedDate = new DateTime(2020, 12, 8, 23, 14, 49, 702, DateTimeKind.Local).AddTicks(8710),
                            CustomerName = "Albert Gerlach"
                        },
                        new
                        {
                            Id = 18L,
                            CreatedDate = new DateTime(2020, 12, 4, 17, 10, 16, 989, DateTimeKind.Local).AddTicks(4806),
                            CustomerName = "Glenda Barrows"
                        },
                        new
                        {
                            Id = 19L,
                            CreatedDate = new DateTime(2020, 12, 3, 12, 45, 56, 860, DateTimeKind.Local).AddTicks(3404),
                            CustomerName = "Mack Howell"
                        },
                        new
                        {
                            Id = 20L,
                            CreatedDate = new DateTime(2020, 12, 7, 14, 47, 26, 150, DateTimeKind.Local).AddTicks(4095),
                            CustomerName = "Blanca Brakus"
                        },
                        new
                        {
                            Id = 21L,
                            CreatedDate = new DateTime(2020, 12, 3, 16, 26, 24, 567, DateTimeKind.Local).AddTicks(5337),
                            CustomerName = "Jim Mayer"
                        },
                        new
                        {
                            Id = 22L,
                            CreatedDate = new DateTime(2020, 12, 9, 19, 36, 46, 64, DateTimeKind.Local).AddTicks(8006),
                            CustomerName = "Ruben Lubowitz"
                        },
                        new
                        {
                            Id = 23L,
                            CreatedDate = new DateTime(2020, 12, 4, 7, 25, 8, 234, DateTimeKind.Local).AddTicks(6562),
                            CustomerName = "Lila Nienow"
                        },
                        new
                        {
                            Id = 24L,
                            CreatedDate = new DateTime(2020, 12, 5, 19, 3, 44, 980, DateTimeKind.Local).AddTicks(6878),
                            CustomerName = "Kyle Klein"
                        },
                        new
                        {
                            Id = 25L,
                            CreatedDate = new DateTime(2020, 12, 7, 1, 44, 11, 763, DateTimeKind.Local).AddTicks(6360),
                            CustomerName = "Cheryl Walter"
                        },
                        new
                        {
                            Id = 26L,
                            CreatedDate = new DateTime(2020, 12, 3, 23, 25, 22, 298, DateTimeKind.Local).AddTicks(5001),
                            CustomerName = "Sheila Thompson"
                        },
                        new
                        {
                            Id = 27L,
                            CreatedDate = new DateTime(2020, 12, 6, 23, 4, 20, 902, DateTimeKind.Local).AddTicks(2066),
                            CustomerName = "Francis Herzog"
                        },
                        new
                        {
                            Id = 28L,
                            CreatedDate = new DateTime(2020, 12, 10, 0, 28, 15, 111, DateTimeKind.Local).AddTicks(5267),
                            CustomerName = "Annette Mohr"
                        },
                        new
                        {
                            Id = 29L,
                            CreatedDate = new DateTime(2020, 12, 4, 10, 17, 30, 743, DateTimeKind.Local).AddTicks(7212),
                            CustomerName = "Terri Farrell"
                        },
                        new
                        {
                            Id = 30L,
                            CreatedDate = new DateTime(2020, 12, 8, 17, 19, 51, 736, DateTimeKind.Local).AddTicks(9708),
                            CustomerName = "Nellie Ruecker"
                        },
                        new
                        {
                            Id = 31L,
                            CreatedDate = new DateTime(2020, 12, 8, 1, 32, 39, 850, DateTimeKind.Local).AddTicks(2047),
                            CustomerName = "Eleanor Rodriguez"
                        },
                        new
                        {
                            Id = 32L,
                            CreatedDate = new DateTime(2020, 12, 7, 5, 50, 11, 1, DateTimeKind.Local).AddTicks(5815),
                            CustomerName = "Mabel Bogisich"
                        },
                        new
                        {
                            Id = 33L,
                            CreatedDate = new DateTime(2020, 12, 9, 21, 39, 17, 710, DateTimeKind.Local).AddTicks(728),
                            CustomerName = "Evelyn Pfeffer"
                        },
                        new
                        {
                            Id = 34L,
                            CreatedDate = new DateTime(2020, 12, 6, 20, 57, 41, 349, DateTimeKind.Local).AddTicks(7708),
                            CustomerName = "Erik Wolf"
                        },
                        new
                        {
                            Id = 35L,
                            CreatedDate = new DateTime(2020, 12, 5, 12, 33, 57, 604, DateTimeKind.Local).AddTicks(1009),
                            CustomerName = "Lila Moore"
                        },
                        new
                        {
                            Id = 36L,
                            CreatedDate = new DateTime(2020, 12, 6, 12, 30, 46, 653, DateTimeKind.Local).AddTicks(2632),
                            CustomerName = "Emilio O'Connell"
                        },
                        new
                        {
                            Id = 37L,
                            CreatedDate = new DateTime(2020, 12, 4, 18, 29, 55, 46, DateTimeKind.Local).AddTicks(4888),
                            CustomerName = "Jaime Greenholt"
                        },
                        new
                        {
                            Id = 38L,
                            CreatedDate = new DateTime(2020, 12, 3, 19, 15, 50, 275, DateTimeKind.Local).AddTicks(503),
                            CustomerName = "Kellie Padberg"
                        },
                        new
                        {
                            Id = 39L,
                            CreatedDate = new DateTime(2020, 12, 4, 3, 18, 54, 46, DateTimeKind.Local).AddTicks(4533),
                            CustomerName = "Matt Moen"
                        },
                        new
                        {
                            Id = 40L,
                            CreatedDate = new DateTime(2020, 12, 5, 1, 51, 8, 212, DateTimeKind.Local).AddTicks(9003),
                            CustomerName = "Vanessa Roberts"
                        },
                        new
                        {
                            Id = 41L,
                            CreatedDate = new DateTime(2020, 12, 6, 11, 2, 41, 558, DateTimeKind.Local).AddTicks(1827),
                            CustomerName = "Pat Thiel"
                        },
                        new
                        {
                            Id = 42L,
                            CreatedDate = new DateTime(2020, 12, 8, 20, 3, 49, 572, DateTimeKind.Local).AddTicks(851),
                            CustomerName = "Angel Wyman"
                        },
                        new
                        {
                            Id = 43L,
                            CreatedDate = new DateTime(2020, 12, 8, 15, 18, 50, 749, DateTimeKind.Local).AddTicks(5656),
                            CustomerName = "Marcella Reichel"
                        },
                        new
                        {
                            Id = 44L,
                            CreatedDate = new DateTime(2020, 12, 6, 1, 32, 13, 460, DateTimeKind.Local).AddTicks(9317),
                            CustomerName = "Mae Koepp"
                        },
                        new
                        {
                            Id = 45L,
                            CreatedDate = new DateTime(2020, 12, 6, 4, 29, 14, 310, DateTimeKind.Local).AddTicks(6423),
                            CustomerName = "Nina Bergstrom"
                        },
                        new
                        {
                            Id = 46L,
                            CreatedDate = new DateTime(2020, 12, 6, 21, 40, 29, 459, DateTimeKind.Local).AddTicks(7131),
                            CustomerName = "Vanessa Kub"
                        },
                        new
                        {
                            Id = 47L,
                            CreatedDate = new DateTime(2020, 12, 4, 3, 38, 17, 953, DateTimeKind.Local).AddTicks(1365),
                            CustomerName = "Francis Hayes"
                        },
                        new
                        {
                            Id = 48L,
                            CreatedDate = new DateTime(2020, 12, 3, 20, 29, 40, 965, DateTimeKind.Local).AddTicks(2022),
                            CustomerName = "Lucia Lebsack"
                        },
                        new
                        {
                            Id = 49L,
                            CreatedDate = new DateTime(2020, 12, 4, 4, 9, 57, 451, DateTimeKind.Local).AddTicks(7945),
                            CustomerName = "Luther Hudson"
                        },
                        new
                        {
                            Id = 50L,
                            CreatedDate = new DateTime(2020, 12, 9, 12, 42, 47, 471, DateTimeKind.Local).AddTicks(6438),
                            CustomerName = "Mack Pfeffer"
                        });
                });

            modelBuilder.Entity("ExerciseA.Domain.Entities.OrderDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetail");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            OrderId = 32L,
                            ProductId = 20L,
                            Quantity = 22
                        },
                        new
                        {
                            Id = 2L,
                            OrderId = 32L,
                            ProductId = 19L,
                            Quantity = 183
                        },
                        new
                        {
                            Id = 3L,
                            OrderId = 3L,
                            ProductId = 2L,
                            Quantity = 190
                        },
                        new
                        {
                            Id = 4L,
                            OrderId = 4L,
                            ProductId = 9L,
                            Quantity = 141
                        },
                        new
                        {
                            Id = 5L,
                            OrderId = 4L,
                            ProductId = 19L,
                            Quantity = 38
                        },
                        new
                        {
                            Id = 6L,
                            OrderId = 38L,
                            ProductId = 1L,
                            Quantity = 143
                        },
                        new
                        {
                            Id = 7L,
                            OrderId = 2L,
                            ProductId = 16L,
                            Quantity = 74
                        },
                        new
                        {
                            Id = 8L,
                            OrderId = 1L,
                            ProductId = 19L,
                            Quantity = 73
                        },
                        new
                        {
                            Id = 9L,
                            OrderId = 12L,
                            ProductId = 18L,
                            Quantity = 81
                        },
                        new
                        {
                            Id = 10L,
                            OrderId = 20L,
                            ProductId = 2L,
                            Quantity = 119
                        },
                        new
                        {
                            Id = 11L,
                            OrderId = 9L,
                            ProductId = 17L,
                            Quantity = 90
                        },
                        new
                        {
                            Id = 12L,
                            OrderId = 6L,
                            ProductId = 16L,
                            Quantity = 198
                        },
                        new
                        {
                            Id = 13L,
                            OrderId = 41L,
                            ProductId = 20L,
                            Quantity = 57
                        },
                        new
                        {
                            Id = 14L,
                            OrderId = 8L,
                            ProductId = 6L,
                            Quantity = 177
                        },
                        new
                        {
                            Id = 15L,
                            OrderId = 24L,
                            ProductId = 2L,
                            Quantity = 187
                        },
                        new
                        {
                            Id = 16L,
                            OrderId = 49L,
                            ProductId = 10L,
                            Quantity = 21
                        },
                        new
                        {
                            Id = 17L,
                            OrderId = 16L,
                            ProductId = 11L,
                            Quantity = 75
                        },
                        new
                        {
                            Id = 18L,
                            OrderId = 15L,
                            ProductId = 2L,
                            Quantity = 139
                        },
                        new
                        {
                            Id = 19L,
                            OrderId = 38L,
                            ProductId = 13L,
                            Quantity = 77
                        },
                        new
                        {
                            Id = 20L,
                            OrderId = 26L,
                            ProductId = 8L,
                            Quantity = 3
                        });
                });

            modelBuilder.Entity("ExerciseA.Domain.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Generic Plastic Chips",
                            Price = 133
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Sleek Fresh Bike",
                            Price = 179
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Gorgeous Granite Table",
                            Price = 231
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Intelligent Rubber Towels",
                            Price = 44
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Small Metal Cheese",
                            Price = 52
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Awesome Wooden Salad",
                            Price = 158
                        },
                        new
                        {
                            Id = 7L,
                            Name = "Licensed Wooden Soap",
                            Price = 177
                        },
                        new
                        {
                            Id = 8L,
                            Name = "Ergonomic Steel Fish",
                            Price = 270
                        },
                        new
                        {
                            Id = 9L,
                            Name = "Small Fresh Table",
                            Price = 94
                        },
                        new
                        {
                            Id = 10L,
                            Name = "Intelligent Granite Table",
                            Price = 264
                        },
                        new
                        {
                            Id = 11L,
                            Name = "Licensed Concrete Ball",
                            Price = 205
                        },
                        new
                        {
                            Id = 12L,
                            Name = "Ergonomic Steel Bacon",
                            Price = 88
                        },
                        new
                        {
                            Id = 13L,
                            Name = "Sleek Wooden Shoes",
                            Price = 27
                        },
                        new
                        {
                            Id = 14L,
                            Name = "Unbranded Rubber Cheese",
                            Price = 146
                        },
                        new
                        {
                            Id = 15L,
                            Name = "Practical Granite Tuna",
                            Price = 96
                        },
                        new
                        {
                            Id = 16L,
                            Name = "Gorgeous Metal Hat",
                            Price = 67
                        },
                        new
                        {
                            Id = 17L,
                            Name = "Licensed Granite Fish",
                            Price = 92
                        },
                        new
                        {
                            Id = 18L,
                            Name = "Ergonomic Concrete Sausages",
                            Price = 171
                        },
                        new
                        {
                            Id = 19L,
                            Name = "Intelligent Fresh Shirt",
                            Price = 105
                        },
                        new
                        {
                            Id = 20L,
                            Name = "Licensed Concrete Table",
                            Price = 212
                        });
                });

            modelBuilder.Entity("ExerciseA.Domain.Entities.UserInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("UserInfo");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2020, 12, 3, 23, 19, 14, 324, DateTimeKind.Local).AddTicks(4877),
                            Email = "Cara.Kemmer48@hotmail.com",
                            FirstName = "Fiona",
                            LastName = "O'Keefe",
                            Password = "rPHSr8F5Ug",
                            UserName = "Xander_Gaylord20"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2020, 12, 4, 3, 12, 43, 155, DateTimeKind.Local).AddTicks(3056),
                            Email = "Rick_Schneider@yahoo.com",
                            FirstName = "Nova",
                            LastName = "Mitchell",
                            Password = "51QiQ4tUk2",
                            UserName = "Frederick29"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedDate = new DateTime(2020, 12, 10, 4, 23, 2, 657, DateTimeKind.Local).AddTicks(8530),
                            Email = "Korey.Kassulke@gmail.com",
                            FirstName = "Emile",
                            LastName = "Bogan",
                            Password = "mYWPvNaiNs",
                            UserName = "Burley64"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedDate = new DateTime(2020, 12, 3, 20, 12, 9, 616, DateTimeKind.Local).AddTicks(4428),
                            Email = "Arne42@gmail.com",
                            FirstName = "Clair",
                            LastName = "Ziemann",
                            Password = "1_Qd1c0x5d",
                            UserName = "Breana_Boyle"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedDate = new DateTime(2020, 12, 4, 0, 36, 4, 58, DateTimeKind.Local).AddTicks(6463),
                            Email = "Luciano39@yahoo.com",
                            FirstName = "Bill",
                            LastName = "Conn",
                            Password = "HCu7rSuVME",
                            UserName = "Bret_Windler46"
                        });
                });

            modelBuilder.Entity("ExerciseA.Domain.Entities.OrderDetail", b =>
                {
                    b.HasOne("ExerciseA.Domain.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExerciseA.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
