// <auto-generated />
using System;
using ExerciseA.Implementation.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExerciseA.Implementation.Migrations
{
    [DbContext(typeof(ExerciseAContext))]
    partial class ExerciseAContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExerciseA.Domain.Entities.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Order");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2020, 12, 10, 1, 42, 35, 652, DateTimeKind.Local).AddTicks(5080),
                            CustomerName = "Esther Littel"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2020, 12, 8, 11, 59, 11, 923, DateTimeKind.Local).AddTicks(7271),
                            CustomerName = "Noah Hilpert"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedDate = new DateTime(2020, 12, 9, 4, 27, 7, 245, DateTimeKind.Local).AddTicks(7975),
                            CustomerName = "Caleb Zieme"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedDate = new DateTime(2020, 12, 9, 20, 42, 25, 687, DateTimeKind.Local).AddTicks(6986),
                            CustomerName = "Lula O'Connell"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedDate = new DateTime(2020, 12, 7, 16, 9, 12, 475, DateTimeKind.Local).AddTicks(5372),
                            CustomerName = "Penny Gottlieb"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedDate = new DateTime(2020, 12, 7, 2, 7, 31, 336, DateTimeKind.Local).AddTicks(9916),
                            CustomerName = "Gwen Corwin"
                        },
                        new
                        {
                            Id = 7L,
                            CreatedDate = new DateTime(2020, 12, 5, 2, 41, 21, 610, DateTimeKind.Local).AddTicks(8874),
                            CustomerName = "Flora Schowalter"
                        },
                        new
                        {
                            Id = 8L,
                            CreatedDate = new DateTime(2020, 12, 6, 8, 48, 46, 178, DateTimeKind.Local).AddTicks(3660),
                            CustomerName = "Cory Nienow"
                        },
                        new
                        {
                            Id = 9L,
                            CreatedDate = new DateTime(2020, 12, 4, 22, 21, 54, 452, DateTimeKind.Local).AddTicks(2518),
                            CustomerName = "Jody Reynolds"
                        },
                        new
                        {
                            Id = 10L,
                            CreatedDate = new DateTime(2020, 12, 7, 22, 5, 11, 407, DateTimeKind.Local).AddTicks(962),
                            CustomerName = "Yvette Bednar"
                        },
                        new
                        {
                            Id = 11L,
                            CreatedDate = new DateTime(2020, 12, 8, 3, 4, 35, 652, DateTimeKind.Local).AddTicks(6707),
                            CustomerName = "Jerome Blanda"
                        },
                        new
                        {
                            Id = 12L,
                            CreatedDate = new DateTime(2020, 12, 3, 17, 53, 42, 194, DateTimeKind.Local).AddTicks(853),
                            CustomerName = "Silvia Schaden"
                        },
                        new
                        {
                            Id = 13L,
                            CreatedDate = new DateTime(2020, 12, 4, 9, 28, 28, 533, DateTimeKind.Local).AddTicks(9717),
                            CustomerName = "Alton Labadie"
                        },
                        new
                        {
                            Id = 14L,
                            CreatedDate = new DateTime(2020, 12, 3, 14, 8, 58, 855, DateTimeKind.Local).AddTicks(3008),
                            CustomerName = "Jason Torphy"
                        },
                        new
                        {
                            Id = 15L,
                            CreatedDate = new DateTime(2020, 12, 5, 17, 16, 55, 249, DateTimeKind.Local).AddTicks(4879),
                            CustomerName = "Cody Franecki"
                        },
                        new
                        {
                            Id = 16L,
                            CreatedDate = new DateTime(2020, 12, 8, 2, 48, 7, 961, DateTimeKind.Local).AddTicks(7449),
                            CustomerName = "Casey Nicolas"
                        },
                        new
                        {
                            Id = 17L,
                            CreatedDate = new DateTime(2020, 12, 5, 15, 47, 24, 22, DateTimeKind.Local).AddTicks(3608),
                            CustomerName = "Phillip Schamberger"
                        },
                        new
                        {
                            Id = 18L,
                            CreatedDate = new DateTime(2020, 12, 5, 12, 40, 3, 288, DateTimeKind.Local).AddTicks(2429),
                            CustomerName = "Darrell Bode"
                        },
                        new
                        {
                            Id = 19L,
                            CreatedDate = new DateTime(2020, 12, 8, 19, 20, 13, 571, DateTimeKind.Local).AddTicks(4278),
                            CustomerName = "Latoya Morar"
                        },
                        new
                        {
                            Id = 20L,
                            CreatedDate = new DateTime(2020, 12, 8, 7, 7, 47, 317, DateTimeKind.Local).AddTicks(47),
                            CustomerName = "Sonya Bailey"
                        },
                        new
                        {
                            Id = 21L,
                            CreatedDate = new DateTime(2020, 12, 6, 4, 28, 19, 107, DateTimeKind.Local).AddTicks(7975),
                            CustomerName = "Carroll Heidenreich"
                        },
                        new
                        {
                            Id = 22L,
                            CreatedDate = new DateTime(2020, 12, 10, 1, 15, 55, 701, DateTimeKind.Local).AddTicks(9724),
                            CustomerName = "Gerald Donnelly"
                        },
                        new
                        {
                            Id = 23L,
                            CreatedDate = new DateTime(2020, 12, 3, 7, 26, 44, 337, DateTimeKind.Local).AddTicks(7414),
                            CustomerName = "Gwen Mills"
                        },
                        new
                        {
                            Id = 24L,
                            CreatedDate = new DateTime(2020, 12, 4, 10, 57, 48, 905, DateTimeKind.Local).AddTicks(1270),
                            CustomerName = "Priscilla Kreiger"
                        },
                        new
                        {
                            Id = 25L,
                            CreatedDate = new DateTime(2020, 12, 3, 16, 15, 51, 436, DateTimeKind.Local).AddTicks(8454),
                            CustomerName = "Wade Stracke"
                        },
                        new
                        {
                            Id = 26L,
                            CreatedDate = new DateTime(2020, 12, 9, 15, 49, 57, 539, DateTimeKind.Local).AddTicks(7465),
                            CustomerName = "Larry Gleichner"
                        },
                        new
                        {
                            Id = 27L,
                            CreatedDate = new DateTime(2020, 12, 3, 19, 46, 5, 564, DateTimeKind.Local).AddTicks(659),
                            CustomerName = "Bertha Nader"
                        },
                        new
                        {
                            Id = 28L,
                            CreatedDate = new DateTime(2020, 12, 7, 17, 1, 19, 41, DateTimeKind.Local).AddTicks(5093),
                            CustomerName = "Keith Grimes"
                        },
                        new
                        {
                            Id = 29L,
                            CreatedDate = new DateTime(2020, 12, 5, 7, 55, 41, 823, DateTimeKind.Local).AddTicks(9831),
                            CustomerName = "Melanie Armstrong"
                        },
                        new
                        {
                            Id = 30L,
                            CreatedDate = new DateTime(2020, 12, 3, 14, 39, 22, 143, DateTimeKind.Local).AddTicks(6880),
                            CustomerName = "Isaac Mraz"
                        },
                        new
                        {
                            Id = 31L,
                            CreatedDate = new DateTime(2020, 12, 3, 9, 46, 35, 112, DateTimeKind.Local).AddTicks(8528),
                            CustomerName = "Justin Kautzer"
                        },
                        new
                        {
                            Id = 32L,
                            CreatedDate = new DateTime(2020, 12, 8, 18, 42, 49, 596, DateTimeKind.Local).AddTicks(2956),
                            CustomerName = "Wilbert Bayer"
                        },
                        new
                        {
                            Id = 33L,
                            CreatedDate = new DateTime(2020, 12, 3, 6, 36, 50, 911, DateTimeKind.Local).AddTicks(8478),
                            CustomerName = "Gilbert Raynor"
                        },
                        new
                        {
                            Id = 34L,
                            CreatedDate = new DateTime(2020, 12, 3, 23, 38, 30, 843, DateTimeKind.Local).AddTicks(7269),
                            CustomerName = "Myrtle Funk"
                        },
                        new
                        {
                            Id = 35L,
                            CreatedDate = new DateTime(2020, 12, 8, 13, 51, 33, 94, DateTimeKind.Local).AddTicks(5351),
                            CustomerName = "Kristi Parker"
                        },
                        new
                        {
                            Id = 36L,
                            CreatedDate = new DateTime(2020, 12, 7, 10, 18, 7, 383, DateTimeKind.Local).AddTicks(8306),
                            CustomerName = "Regina Davis"
                        },
                        new
                        {
                            Id = 37L,
                            CreatedDate = new DateTime(2020, 12, 4, 0, 21, 4, 412, DateTimeKind.Local).AddTicks(6933),
                            CustomerName = "Bryant Schmidt"
                        },
                        new
                        {
                            Id = 38L,
                            CreatedDate = new DateTime(2020, 12, 4, 16, 14, 17, 864, DateTimeKind.Local).AddTicks(9293),
                            CustomerName = "Hilda Reynolds"
                        },
                        new
                        {
                            Id = 39L,
                            CreatedDate = new DateTime(2020, 12, 7, 19, 43, 28, 227, DateTimeKind.Local).AddTicks(816),
                            CustomerName = "Leslie Conroy"
                        },
                        new
                        {
                            Id = 40L,
                            CreatedDate = new DateTime(2020, 12, 3, 14, 8, 25, 700, DateTimeKind.Local).AddTicks(8806),
                            CustomerName = "Curtis Ullrich"
                        },
                        new
                        {
                            Id = 41L,
                            CreatedDate = new DateTime(2020, 12, 4, 22, 52, 40, 47, DateTimeKind.Local).AddTicks(6540),
                            CustomerName = "Yvette Aufderhar"
                        },
                        new
                        {
                            Id = 42L,
                            CreatedDate = new DateTime(2020, 12, 7, 14, 40, 27, 678, DateTimeKind.Local).AddTicks(6837),
                            CustomerName = "Lindsay Greenholt"
                        },
                        new
                        {
                            Id = 43L,
                            CreatedDate = new DateTime(2020, 12, 8, 14, 58, 4, 809, DateTimeKind.Local).AddTicks(5959),
                            CustomerName = "Jackie Luettgen"
                        },
                        new
                        {
                            Id = 44L,
                            CreatedDate = new DateTime(2020, 12, 7, 8, 59, 43, 486, DateTimeKind.Local).AddTicks(3839),
                            CustomerName = "Kara Dare"
                        },
                        new
                        {
                            Id = 45L,
                            CreatedDate = new DateTime(2020, 12, 3, 14, 3, 37, 723, DateTimeKind.Local).AddTicks(9332),
                            CustomerName = "Carl Dickens"
                        },
                        new
                        {
                            Id = 46L,
                            CreatedDate = new DateTime(2020, 12, 6, 8, 46, 21, 147, DateTimeKind.Local).AddTicks(8956),
                            CustomerName = "Archie Schaden"
                        },
                        new
                        {
                            Id = 47L,
                            CreatedDate = new DateTime(2020, 12, 3, 13, 57, 8, 125, DateTimeKind.Local).AddTicks(4659),
                            CustomerName = "Jean Langworth"
                        },
                        new
                        {
                            Id = 48L,
                            CreatedDate = new DateTime(2020, 12, 3, 13, 2, 17, 88, DateTimeKind.Local).AddTicks(6800),
                            CustomerName = "Tracey Romaguera"
                        },
                        new
                        {
                            Id = 49L,
                            CreatedDate = new DateTime(2020, 12, 10, 3, 7, 16, 720, DateTimeKind.Local).AddTicks(5368),
                            CustomerName = "Lorenzo Ondricka"
                        },
                        new
                        {
                            Id = 50L,
                            CreatedDate = new DateTime(2020, 12, 8, 19, 30, 20, 28, DateTimeKind.Local).AddTicks(3791),
                            CustomerName = "Christina Lowe"
                        });
                });

            modelBuilder.Entity("ExerciseA.Domain.Entities.OrderDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetail");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            OrderId = 11L,
                            ProductId = 14L,
                            Quantity = 133
                        },
                        new
                        {
                            Id = 2L,
                            OrderId = 50L,
                            ProductId = 13L,
                            Quantity = 198
                        },
                        new
                        {
                            Id = 3L,
                            OrderId = 46L,
                            ProductId = 2L,
                            Quantity = 46
                        },
                        new
                        {
                            Id = 4L,
                            OrderId = 19L,
                            ProductId = 16L,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 5L,
                            OrderId = 9L,
                            ProductId = 11L,
                            Quantity = 26
                        },
                        new
                        {
                            Id = 6L,
                            OrderId = 9L,
                            ProductId = 8L,
                            Quantity = 17
                        },
                        new
                        {
                            Id = 7L,
                            OrderId = 26L,
                            ProductId = 6L,
                            Quantity = 29
                        },
                        new
                        {
                            Id = 8L,
                            OrderId = 2L,
                            ProductId = 11L,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 9L,
                            OrderId = 4L,
                            ProductId = 10L,
                            Quantity = 115
                        },
                        new
                        {
                            Id = 10L,
                            OrderId = 17L,
                            ProductId = 10L,
                            Quantity = 59
                        },
                        new
                        {
                            Id = 11L,
                            OrderId = 11L,
                            ProductId = 16L,
                            Quantity = 8
                        },
                        new
                        {
                            Id = 12L,
                            OrderId = 42L,
                            ProductId = 2L,
                            Quantity = 173
                        },
                        new
                        {
                            Id = 13L,
                            OrderId = 17L,
                            ProductId = 2L,
                            Quantity = 21
                        },
                        new
                        {
                            Id = 14L,
                            OrderId = 50L,
                            ProductId = 18L,
                            Quantity = 182
                        },
                        new
                        {
                            Id = 15L,
                            OrderId = 29L,
                            ProductId = 19L,
                            Quantity = 186
                        },
                        new
                        {
                            Id = 16L,
                            OrderId = 1L,
                            ProductId = 6L,
                            Quantity = 190
                        },
                        new
                        {
                            Id = 17L,
                            OrderId = 45L,
                            ProductId = 10L,
                            Quantity = 137
                        },
                        new
                        {
                            Id = 18L,
                            OrderId = 8L,
                            ProductId = 15L,
                            Quantity = 134
                        },
                        new
                        {
                            Id = 19L,
                            OrderId = 33L,
                            ProductId = 4L,
                            Quantity = 73
                        },
                        new
                        {
                            Id = 20L,
                            OrderId = 21L,
                            ProductId = 19L,
                            Quantity = 33
                        });
                });

            modelBuilder.Entity("ExerciseA.Domain.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Rustic Steel Shirt",
                            Price = 151
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Fantastic Wooden Mouse",
                            Price = 239
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Refined Granite Keyboard",
                            Price = 69
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Handcrafted Cotton Table",
                            Price = 285
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Tasty Cotton Chair",
                            Price = 290
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Handmade Cotton Tuna",
                            Price = 27
                        },
                        new
                        {
                            Id = 7L,
                            Name = "Generic Steel Gloves",
                            Price = 201
                        },
                        new
                        {
                            Id = 8L,
                            Name = "Tasty Plastic Shoes",
                            Price = 294
                        },
                        new
                        {
                            Id = 9L,
                            Name = "Gorgeous Rubber Towels",
                            Price = 270
                        },
                        new
                        {
                            Id = 10L,
                            Name = "Unbranded Granite Tuna",
                            Price = 110
                        },
                        new
                        {
                            Id = 11L,
                            Name = "Sleek Cotton Gloves",
                            Price = 260
                        },
                        new
                        {
                            Id = 12L,
                            Name = "Small Concrete Ball",
                            Price = 105
                        },
                        new
                        {
                            Id = 13L,
                            Name = "Fantastic Cotton Chicken",
                            Price = 36
                        },
                        new
                        {
                            Id = 14L,
                            Name = "Incredible Metal Shirt",
                            Price = 234
                        },
                        new
                        {
                            Id = 15L,
                            Name = "Fantastic Plastic Salad",
                            Price = 95
                        },
                        new
                        {
                            Id = 16L,
                            Name = "Refined Granite Bacon",
                            Price = 159
                        },
                        new
                        {
                            Id = 17L,
                            Name = "Small Wooden Chips",
                            Price = 36
                        },
                        new
                        {
                            Id = 18L,
                            Name = "Licensed Rubber Car",
                            Price = 135
                        },
                        new
                        {
                            Id = 19L,
                            Name = "Licensed Metal Shoes",
                            Price = 91
                        },
                        new
                        {
                            Id = 20L,
                            Name = "Ergonomic Soft Computer",
                            Price = 100
                        });
                });

            modelBuilder.Entity("ExerciseA.Domain.Entities.OrderDetail", b =>
                {
                    b.HasOne("ExerciseA.Domain.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExerciseA.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
